# Projekt: Projekt 2
# Autor:   Roman Nahalka, xnahal01@stud.fit.vutbr.cz
# Datum:   04.04.2015

CC=gcc                              # překladač jazyka C
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic  # parametry překladače

proj2: proj2.c
	$(CC) $(CFLAGS) proj2.c -o proj2 -pthread -lpthread
