# Projekt: Projekt 1
# Autor:   Roman Nahalka
# Datum:   11.9.2015

CC=gcc                              # pøekladaè jazyka C
CFLAGS=-std=c99 -Wall -Wextra -pedantic -DNDEBUG  # parametry pøekladaèe

proj2: proj3.c
	$(CC) $(CFLAGS) proj3.c -lm -o proj3 -lm
