package dialogs;

/**
 * projekt: Solitaire Klondike - IJA 2016/2017
 * autori: Roman Nahalka (xnahal01), Adam Zivcak (xzivca03)
 * dátum: 6.5.2017
 * 
 * Dialogove okno pro zeptani se uzivatle, zdali chce spustit novou hru nebo
 * nacist drive ulozenou hru do hraciho pole, kde je jiz rozehrana hra.
 */
public class AlreadyPlayedDialog extends javax.swing.JDialog
{    
    private boolean choice;
    
    public AlreadyPlayedDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        text = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        text.setText("Ve vybrané hrací ploše je rozehraná hra, chcete přesto pokračovat?");

        yesButton.setText("Ano");
        yesButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("Ne");
        noButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(yesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(noButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(text)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton)
                    .addComponent(noButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_yesButtonActionPerformed
    {//GEN-HEADEREND:event_yesButtonActionPerformed
        this.choice = true;
        dispose();
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_noButtonActionPerformed
    {//GEN-HEADEREND:event_noButtonActionPerformed
        this.choice = false;
        dispose();
    }//GEN-LAST:event_noButtonActionPerformed
   
    /**
     * Metoda, ktera vrati odpoved uzivatele. 
     * @return Rozhodnuti
     */
    public boolean getChoice()
    {
        return this.choice;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton noButton;
    private javax.swing.JLabel text;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
