package dialogs;

import frames.OneGame;
import java.awt.Toolkit;

/**
 * projekt: Solitaire Klondike - IJA 2016/2017
 * autori: Roman Nahalka (xnahal01), Adam Zivcak (xzivca03)
 * dátum: 6.5.2017
 * 
 * Dialogove okno, ktere se otevre potom, co chce hrac v okne pro jednu hru, spustit
 * novou hru pri rozehrane hre.
 */
public class NewGameDialog extends javax.swing.JDialog
{

    /**
     * Vyctovy typ reprezentujici uzivatelovo rozhodnuti.
     */
    public enum Decision
    {

        /**
         * Uzivatel chce zrusit rozehranou hru.
         */
        EXIT(0),

        /**
         * Uzivatel chce hru otevrit v novem hracim poli.
         */
        NEW(1),

        /**
         * Uzivatel svoji volbu zrusi.
         */
        CLOSE(2);
        
        private int value;
        
        Decision(int value)
        {
            this.value = value;
        }
    }
    
    private Decision decision;
    
    public NewGameDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        endButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nová hra");
        setIconImage(Toolkit.getDefaultToolkit().getImage(OneGame.class.getResource("/images/Icon.png")));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("<html>Máte rozehranou hru. Chcete vytvořit nové hrací pole nebo<br> stávající hru ukončit a začít znovu?</html>");

        endButton.setText("Ukončit a začít znovu");
        endButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                endButtonActionPerformed(evt);
            }
        });

        newButton.setText("Nové hrací pole");
        newButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Zrušit");
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(endButton)
                        .addGap(40, 40, 40)
                        .addComponent(newButton)
                        .addGap(40, 40, 40)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endButton)
                    .addComponent(newButton)
                    .addComponent(cancelButton))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
    {//GEN-HEADEREND:event_cancelButtonActionPerformed
        this.decision = Decision.CLOSE;
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newButtonActionPerformed
    {//GEN-HEADEREND:event_newButtonActionPerformed
        this.decision = Decision.NEW;
        dispose();
    }//GEN-LAST:event_newButtonActionPerformed

    private void endButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_endButtonActionPerformed
    {//GEN-HEADEREND:event_endButtonActionPerformed
        this.decision = Decision.EXIT;
        dispose();
    }//GEN-LAST:event_endButtonActionPerformed

    /**
     * Metoda, ktera vrati uzivatelovo rozhodnuti.
     * @return Rozhodnuti
     */
    public Decision getDecision()
    {
        return this.decision;
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton endButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newButton;
    // End of variables declaration//GEN-END:variables
}
