# Projekt: Projekt 1
# Autor:   Roman Nah8lka
# Datum:   11.9.2015

CC=gcc                              # pøekladaè jazyka C
CFLAGS=-std=c99 -Wall -Wextra -pedantic  # parametry pøekladaèe

proj2: proj2.c
	$(CC) $(CFLAGS) proj2.c -lm -o proj2
