# Projekt: Projekt 1
# Autor:   Roman Nah8lka
# Datum:   11.9.2015

CC=gcc                              # pøekladaè jazyka C
CFLAGS=-std=c99 -Wall -Wextra -pedantic  # parametry pøekladaèe

proj1: proj1.c
	$(CC) $(CFLAGS) proj1.c -o proj1